markdown: kramdown
kramdown:
  math_engine: mathjax # Explicitly enable math support
  syntax_highlighter: rouge # For code highlighting

theme: minima
include:
  - _includes
  - assets
# Optional but recommended for GH Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Other typical settings (customize as needed)
title: Daniel's Portfolio
description: My website
baseurl: "" # e.g., "/blog" if hosted at username.github.io/blog
url: "" # e.g., "https://yourusername.github.io"

